wireplumber.components = [
  {
    name = "force-default-sink.lua",
    type = "script/lua",
    provides = "custom.force-default-sink",
    arguments = {
      route = [
        #{
        #  match = { application.process.binary = "steamwebhelper" },
        #  target = "alsa_loopback_device.alsa_output.pci-0000_0c_00.1.hdmi-stereo"
        #},
        #{
        #  match = { node.name = "alsa_playback.doneward" },
        #  target = "alsa_loopback_device.alsa_output.pci-0000_0c_00.1.hdmi-stereo"
        #},
        #{
        #  match = { application.name = "Spirit City" },
        #  target = "alsa_loopback_device.alsa_output.pci-0000_0c_00.1.hdmi-stereo"
        #},
      ]
    }
  }
]

wireplumber.profiles = {
  main = {
    custom.force-default-sink = required
  }
}
