#!/bin/bash

test -z "$NIX_PROFILES" || exit 0
test -w /nix || exit 0

set -x -e
curl -sSf -L https://install.lix.systems/lix | sh -s -- install
nix profile install nixpkgs#legacyPackages.x86_64-linux.lix --priority 4
