#!/bin/bash

which pacman &>/dev/null || exit 0
which paru &>/dev/null && exit 0

VER="2.0.4"
ARCH="x86_64"

echo installing paru...

set -x -e

curl -L https://github.com/Morganamilo/paru/releases/download/v$VER/paru-v$VER-$ARCH.tar.zst | tar --use-compress-program=unzstd -xO paru > ~/bin/paru
chmod +x ~/bin/paru
