#!/bin/bash

command -v bat > /dev/null && exit 0

if command -v nix > /dev/null; then
	set -x -e
	exec nix profile install 'nixpkgs#bat'
fi

if command -v curl > /dev/null && command -v tar > /dev/null; then
	set -x -e
	curl -sSL https://github.com/sharkdp/bat/releases/download/v0.18.0/bat-v0.18.0-x86_64-unknown-linux-musl.tar.gz | tar xzO --wildcards \*/bat > ~/bin/bat
	chmod +x ~/bin/bat
	exit 0
fi
