#!/bin/bash

command -v cargo-firstpage > /dev/null && exit 0
command -v cargo > /dev/null || exit 1

set -x -e

rustup target add x86_64-unknown-linux-musl
cargo install --target x86_64-unknown-linux-musl cargo-firstpage
