#!/bin/bash

command -v cargo-watch > /dev/null && exit 0
command -v cargo > /dev/null || exit 1

if command -v nix > /dev/null; then
	set -x -e
	exec nix profile install 'nixpkgs#cargo-watch'
fi

if command -v cargo > /dev/null; then
	set -x -e
	rustup target add x86_64-unknown-linux-musl
	exec cargo install --target x86_64-unknown-linux-musl cargo-watch
fi
