#!/bin/bash

command -v eza > /dev/null && exit 0

if command -v nix > /dev/null; then
	set -x -e
	exec nix profile install 'nixpkgs#eza'
fi

if command -v curl > /dev/null && command -v tar > /dev/null; then
	set -x -e
	curl -sSL https://github.com/eza-community/eza/releases/download/v0.23.3/eza_x86_64-unknown-linux-musl.tar.gz | tar xzO --wildcards \*/eza > ~/bin/eza
	chmod +x ~/bin/eza
	exit 0
fi
