#!/bin/bash

which exa &> /dev/null && exit 0
which rustup &> /dev/null || exit 1

rustup target install x86_64-unknown-linux-musl
cargo install --target=x86_64-unknown-linux-musl --no-default-features exa
