#!/bin/bash

command -v exa > /dev/null && exit 0
command -v wget > /dev/null || exit 1
command -v bsdtar > /dev/null || exit 1

set -x -e
cd /tmp
curl -sSL https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-musl-v0.10.1.zip | bsdtar -xOf - bin/exa > ~/bin/exa
chmod +x ~/bin/exa
