#!/bin/bash

which windows-vm &> /dev/null && exit 0
which cargo &> /dev/null || exit 1

set -x -e
cd ~/scripts
cargo build --release --target x86_64-unknown-linux-musl -p windows-vm
strip target/x86_64-unknown-linux-musl/release/windows-vm
sudo install -D -m4755 target/x86_64-unknown-linux-musl/release/windows-vm /usr/local/bin/windows-vm
